language: julia
os:
  - osx
julia:
  - 0.5
install:
  - julia -e 'Pkg.add("Bio"); Pkg.add("SuffixArrays"); Pkg.add("Gadfly")'
notifications:
  email: false
script:
  - julia --check-bounds=yes --code-coverage ./test/runtests.jl
after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
